---


# This playbook is to install the Appcelerator CLI & Titanium SDK in all the agents
- hosts: agents

  vars_files:
    - /opt/ansible/vault_agents

  tasks:
  - name: Install the Appcelerator CLI
    shell: . ~/.profile && npm install -g appcelerator
  
  - name: Login to Appcelerator/Axway platform
    shell: . ~/.profile && appc login --username "{{ appc_username }}" --password "{{ appc_password }}" --org-id "{{ appc_org }}"
   
  - name: Download the latest Titanium SDK
    shell: . ~/.profile && echo "y" | appc ti sdk install latest
