--- 
# This playbook is to install Xcode updates in all the agents
- hosts: agents
     
  vars_files:
    - /opt/ansible/vault_agents
    - /opt/ansible/group_vars/agents.yml
  
  vars:
    xcode_xip_location: "{{ xcode_xpi_path }}"

  roles:
    - macstadium.xcode
    
