---
- hosts: agents

  vars_files:
    - /opt/ansible/vault_agents
    - /opt/ansible/vars/lang.yml
    - /opt/ansible/vars/paths.yml

  vars:
    homebrew_installed_packages:
      - ssh-copy-id # Easy install of the agents SSH to the server
      - maven 
      - carthage # Needed for iOS dev
      - sonar-scanner # Code analysis with SonarQube
      - imagemagick # Used for app stores design automation
      - node_exporter # Monitoring of the agents
      - mas # Install Mac App Store apps from the CLI
      - smartmontools # Sensors monitoring (CPU temp, fan speed, etc.)
      - ruby # Updated version of Ruby for Fastlane
      - python3 # Updated version of Python for Ansible
      - fail2ban # Protect the agents from SSH attacks

    homebrew_cask_apps:
      - java # Java for Go.CD agents
      - fastlane # iOS and Android automation
      - android-sdk # Android SDK (CLI only)
      - android-ndk # Android NDK (Optional)
      - intel-power-gadget # Additionnal sensors for the monitoring
      - virtualbox # VM used by Genymotion

  tasks:
    - name: Set the LC_ALL to {{ lang }}.UTF-8
      lineinfile:
        path: "{{ ansible_env.HOME }}/.profile"
        line: "export LC_ALL={{ lang }}.UTF-8"
    
    - name: Set the LANG to {{ lang }}.UTF-8
      lineinfile:
        path: "{{ ansible_env.HOME }}/.profile"
        line: "export LANG={{ lang }}.UTF-8"

    - name: Add the Java home path to the $JAVA_HOME
      lineinfile:
        path: "{{ ansible_env.HOME }}/.profile"
        line: "export JAVA_HOME=$(/usr/libexec/java_home)"

    - name: Add the Android home path to the $ANDROID_HOME
      lineinfile:
        path: "{{ ansible_env.HOME }}/.profile"
        line: "export ANDROID_HOME=\"{{ android_sdk_path }}\""
    
    - name: Add the Android home path to the $ANDROID_SDK
      lineinfile:
        path: "{{ ansible_env.HOME }}/.profile"
        line: "export ANDROID_SDK=$ANDROID_HOME"

    - name: Add the Android NDK path to the $ANDROID_NDK
      lineinfile:
        path: "{{ ansible_env.HOME }}/.profile"
        line: "export ANDROID_NDK=\"{{ android_sdk_path }}\""

    - name: Add $JAVA_HOME, $ANDROID_HOME, Python, Ruby, Fastlane to the $PATH
      lineinfile:
        path: "{{ ansible_env.HOME }}/.profile"
        line: "export PATH=$JAVA_HOME/bin:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools/:/usr/local/opt/python/libexec/bin:/usr/local/opt/ruby/bin:$HOME/.fastlane/bin:$PATH"

  roles:
    - geerlingguy.homebrew
